version: '3'
services:
  aa-web:
    build: ./web
    image: angular-poker/web:1.0
    working_dir: /web
    volumes:
      - "./web:/web"
    ports:
      - "80:4200"
      - "49153:49153"
    command: bash -c "ng serve --host 0.0.0.0 --poll 1000"
    tty: true