version: '3'
services:
  web:
    build: .
    image: angular-cli
    container_name: web
    volumes:
      - ".:/web"
    ports:
      - "80:4200"
      - "49153:49153"
    command: ng serve --host 0.0.0.0 --poll 1000