version: '3'
services:
  web:
    build: ./web
    image: angular-cli
    container_name: web
    volumes:
      - "./web:/web"
    ports:
      - "80:4200"
      - "49153:49153"
    command: bash -c "yarn install && ng serve --host 0.0.0.0 --poll 1000"