version: '3'
services:
  aa-web:
    build: ./web
    image: angular-poker/web:1.0
    working_dir: /web
    volumes:
      - "./web:/web"
      - aa-web_modules:/web/node_modules
    ports:
      - "80:4200"
      - "49153:49153"
    command: bash -c "./serve.sh"
    tty: true
volumes:
  aa-web_modules: